[supervisord]
nodaemon=true

[program:django]
command=gunicorn bicyclesscraping.wsgi:application --bind 0.0.0.0:8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=|cat
stderr_logfile=|cat

[program:celery]
command=celery -A bicyclesscraping worker --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=|cat
stderr_logfile=|cat

[program:create_superuser]
command=python create_superuser.py
autostart=true
autorestart=false
startsecs=0
stdout_logfile=|cat
stderr_logfile=|cat