# Generated by Django 5.2 on 2025-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_remove_bicycle_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bicycle",
            name="current_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.FloatField(),
        ),
    ]
