# Generated by Django 5.2 on 2025-08-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0007_alter_subscription_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="bicycle",
            name="web",
            field=models.TextField(default="biking_point", max_length=20),
            preserve_default=False,
        ),
    ]
