# Generated by Django 5.2 on 2025-05-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bicycle",
            name="price",
        ),
    ]
