# Generated by Django 5.2 on 2025-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="reference",
            field=models.IntegerField(default=None, max_length=5),
        ),
    ]
