# Generated by Django 5.2 on 2025-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_subscription_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="reference",
            field=models.IntegerField(default=None),
        ),
    ]
