# Generated by Django 5.2 on 2025-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0006_alter_subscription_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(max_length=60),
        ),
    ]
