# Generated by Django 5.2 on 2026-05-19 18:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0008_bicycle_web"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="reference",
        ),
        migrations.AddField(
            model_name="bicycle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="bicycle",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="bicycle",
            name="reference",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="bicycle",
            name="web",
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(max_length=120),
        ),
        migrations.AddIndex(
            model_name="bicycle",
            index=models.Index(fields=["web"], name="scraping_bi_web_0f1dd8_idx"),
        ),
        migrations.AddIndex(
            model_name="bicycle",
            index=models.Index(
                fields=["reference"], name="scraping_bi_referen_393b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["bicycle", "date"], name="scraping_pr_bicycle_8eadad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bicycle",
            constraint=models.UniqueConstraint(
                fields=("reference", "web"), name="unique_reference_per_web"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricehistory",
            constraint=models.UniqueConstraint(
                fields=("bicycle", "date"), name="unique_price_per_bicycle_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("email", "bicycle"), name="unique_email_bicycle_subscription"
            ),
        ),
    ]
