# Generated by Django 5.2 on 2026-07-16 12:43

from django.db import migrations


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for name in ("user", "moderator", "admin"):
        Group.objects.get_or_create(name=name)

def remove_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(name__in=["user", "moderator", "admin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0009_remove_subscription_reference_bicycle_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(create_role_groups, remove_role_groups),
    ]
