# Generated by Django 5.2 on 2026-08-11 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scraping",
            "0011_remove_subscription_unique_email_bicycle_subscription_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pricehistory",
            name="scraping_pr_bicycle_8eadad_idx",
        ),
        migrations.AddIndex(
            model_name="bicycle",
            index=models.Index(
                fields=["current_price"], name="scraping_bi_current_2709c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["created_at"], name="scraping_su_created_d3fd50_idx"
            ),
        ),
    ]
