# Generated by Django 5.2 on 2026-09-30 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scraping",
            "0012_remove_pricehistory_scraping_pr_bicycle_8eadad_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bicycle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bicycle",
            name="last_seen_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="bicycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_history",
                to="scraping.bicycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="bicycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="scraping.bicycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
