# Generated by Django 5.2 on 2026-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0013_bicycle_is_active_bicycle_last_seen_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bicycle",
            name="last_seen_at",
            field=models.DateField(),
        ),
    ]
