name: Show secrets temporarily

on:
  workflow_dispatch: # lo ejecutas manualmente

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar DB_HOST
        run: echo "${{ secrets.DB_HOST }}" | base64

      - name: Mostrar DB_NAME
        run: echo "${{ secrets.DB_NAME }}" | base64

      - name: Mostrar DB_PASSWORD
        run: echo "${{ secrets.DB_PASSWORD }}" | base64

      - name: Mostrar DB_PORT
        run: echo "${{ secrets.DB_PORT }}" | base64

      - name: Mostrar DB_USER
        run: echo "${{ secrets.DB_USER }}" | base64

      - name: Mostrar SCRAPER_TOKEN
        run: echo "${{ secrets.SCRAPER_TOKEN }}" | base64
