name: Exec Scraper Daily

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Run scraper by pages
        run: |
          for i in {1...30...10}; do
            END=$((i+9))
            curl -X POST "https://bicycles-scraping.onrender.com/extract_bicycles/?token=${{ secrets.SCRAPER_TOKEN }}&start_page=$i&last_page=$END"
            sleep 
          done