name: Scraping

on:
    workflow_dispatch:
        inputs:
            start_page:
                required: true
            last_page:
                required: true
            web:
                required: true
            delete:
                required: true

jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run Scraper
              run: |
                python scraper.py \
                --start_page ${{github.event.inputs.start_page}} \
                --last_page ${{github.event.inputs.last_page}} \
                --web ${{github.event.inputs.web}} \
                --delete ${{github.event.inputs.delete}}

